commerce_shipping.commerce_shipping_method.plugin.usps:
  type: commerce_shipping_method_configuration
  mapping:
    api_information:
      label: 'API information'
      type: mapping
      mapping:
        user_id:
          type: string
          label: 'User ID'
        password:
          type: string
          label: 'Password'
        mode:
          type: string
          label: 'Choose whether to use the test or live mode'
    rate_options:
      type: mapping
      label: 'Rate Options'
      mapping:
        rate_class:
          type: boolean
          label: 'The rate class to use for pricing. For example "Commercial Plus"'
    options:
      type: mapping
      label: 'USPS Options'
      mapping:
        tracking_url:
          type: string
          label: 'Tracking URL'
        log:
          type: mapping
          label: 'Log the following messages for debugging'
          mapping:
            request:
              type: field.value.boolean
              mapping:
                value:
                  label: 'API request messages'
            response:
              type: field.value.boolean
              mapping:
                value:
                  label: 'API response messages'
