<?php

/**
 * @file
 * Contains alert_banner.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function alert_banner_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alert_banner module.
    case 'help.page.alert_banner':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('tvv Custom Blocks in Code') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function alert_banner_theme() {
  return [
    'alert_banner' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ]
  ];
}
