views.style.entity_pager:
  type: views_style
  label: 'Entity Pager'
  mapping:
    relationship:
      type: string
      label: 'Relationship'
    link_next:
      type: label
      label: 'Next label'
    link_prev:
      type: label
      label: 'Previous label'
    display_all:
      type: boolean
      label: 'Display All link'
    link_all_url:
      type: uri
      label: 'List All URL'
    link_all_text:
      type: label
      label: 'List All label'
    display_count:
      type: boolean
      label: 'Display count'
    show_disabled_links:
      type: boolean
      label: 'Show disabled links'
    circular_paging:
      type: boolean
      label: 'Circular paging'
    log_performance:
      type: boolean
      label: 'Log performance suggestions'
