commerce_avatax.settings:
  type: config_object
  label: 'Avalara Avatax settings'
  mapping:
    account_id:
      type: string
      label: 'Account ID'
    api_mode:
      type: string
      label: 'API mode'
    company_code:
      type: string
      label: 'Company code'
    customer_code_field:
      type: string
      label: 'Customer code field'
    disable_commit:
      type: boolean
      label: 'Disable document committing'
    disable_tax_calculation:
      type: boolean
      label: 'Disable tax calculation'
    license_key:
      type: string
      label: 'License'
    logging:
      type: boolean
      label: 'Enabled detailed transaction logging'
    shipping_tax_code:
      type: string
      label: 'Shipping tax code'
