# Schema file for the configuration files of the ga module.
ga.settings:
  type: config_object
  label:  'Google Analytics Settings'
  mapping:
    premium:
      type: boolean
      label: 'Enable Premium Features'
    add_default_commands:
      type: boolean
      label: 'Add default analytics commands to registry'
    tracking_id:
      type: string
      label: 'Web Property Tracking ID'
    send_pageview:
      type: boolean
      label: 'Send Pageview Event'
    sample_rate:
      type: integer
      label: 'Sample Rate'
    force_ssl:
      type: boolean
      lable: "Force SSL"
    site_speed_sample_rate:
      type: integer
      label: 'Site Speed Sample Rate'
    plugins:
      type: mapping
      label: 'Plugins'
      mapping:
        linkid:
          type: boolean
          label: 'Enhanced Link Attribution'
        displayfeatures:
          type: boolean
          label: 'Display Features'
        linker:
          type: mapping
          label: 'Linker'
          mapping:
            enable:
              type: boolean
              label: 'Enable Linker'
            domains:
              type: sequence
              label: 'Domains'
              sequence:
                type: string
    track_user_id:
      type: boolean
      label: 'Track User ID'
    user_roles:
      type: mapping
      label: 'Restrict analytics by user role'
      mapping:
        mode:
          type: string
          label: 'User role restriction mode'
        roles:
          type: sequence
          label: 'User roles to apply analytics restrictions to'
    anonymize_ip:
      type: boolean
      label: 'Anonymize IP'
