# Schema for the configuration files of the CookieConsent module.

cookieconsent.settings:
  type: config_object
  label: 'Cookie settings'
  mapping:
    headline_text:
      type: text
      label: 'Headline text'
    accept_button_text:
      type: label
      label: 'Accept button text'
    read_more_button_text:
      type: label
      label: 'Read more button text'
    cookie_policy:
      type: label
      label: 'Your cookie policy'