# Schema file for the configuration files of the ga_tokens module.
ga_tokens.global:
  type: config_object
  label:  'Google Analytics Global Custom Properties'
  mapping:
    dimensions:
      type: sequence
      label: 'Dimensions'
      sequence:
        type: ga_tokens.dimension'
        label: 'Dimension'
    metrics:
      type: sequence
      label: 'Metrics'
      sequence:
        type: ga_tokens.dimension'
        label: 'Metric'

ga_tokens.dimension:
  type: mapping
  mapping:
    label:
      type: string
      label: 'Label'
    value:
      type: string
      label: 'Value'
